channels:
  - ome
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - nb_conda_kernels
  - bftools=6.3.1
  - bioformats2raw=0.2.2
  - raw2ometiff=0.2.4
  - blosc
  - napari
  - zarr
  - dask
  - s3fs
  - pip
  - pip:
    - ome-zarr
