channels:
  - ome
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - bftools
  - bioformats2raw
  - raw2ometiff
  - blosc
  - napari
  - zarr
  - dask
  - s3fs
  - pip
  - pip:
    - ome-zarr
